// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SVX.Data;

namespace SVX.Migrations
{
    [DbContext(typeof(SVXContext))]
    [Migration("20201022213647_Teste")]
    partial class Teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SVX.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("SVX.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("SVX.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Application");

                    b.Property<int>("ClientId");

                    b.Property<string>("Database");

                    b.Property<string>("Hardware");

                    b.Property<string>("Hostname");

                    b.Property<string>("Ip");

                    b.Property<string>("Os");

                    b.Property<string>("Perl");

                    b.Property<string>("Type");

                    b.Property<int>("VersionSVX");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Server");
                });

            modelBuilder.Entity("SVX.Models.Server", b =>
                {
                    b.HasOne("SVX.Models.Client", "Client")
                        .WithMany("Servers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
